subscription/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('subscription.views',
    url(r'^sucesso/(?P<id>\d+)/$', 'success', name='subs_success'),
    url(r'^nova/$', 'subscription', name='subs_new'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import	staticfiles_urlpatterns
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'eventex.views.home', name='home'),
    # url(r'^eventex/', include('eventex.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^inscricao/', include('subscription.urls', namespace='subscription')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'core.views.home', name='home'),
)

urlpatterns += staticfiles_urlpatterns()

subscription/models.py
#*-* coding: utf-8 *-*
from django.db import models

class Subscription(models.Model):
    name = models.CharField(u"Nome", max_length=150)
    email = models.EmailField(verbose_name=u"E-mail", unique=True)
    cpf = models.CharField(u"CPF", max_length=14, unique=True)
    phone = models.CharField(u"Telefone", max_length=14)
    created_at = models.DateTimeField(verbose_name=u"Criado em", auto_now_add=True)
    
    class Meta:
        verbose_name = u"Inscrição"
	verbose_name_plural = u"Inscrições"

    def __unicode__(self):
	return u"%s - %s" % (self.name, self.email)

testes/models.py
from django.db import models

# Create your models here.

subscription/forms.py
from django import forms

from subscription.models import Subscription

class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        exclude = ("created_at",)

core/views.py
#*-* coding: utf-8 *-*
from django.shortcuts import render_to_response
from django.template import RequestContext

def home(request):
    home = True
    return render_to_response('index.html', {'home': home}, context_instance=RequestContext(request))

subscription/views.py
from django.views.defaults import RequestContext
from django.shortcuts import render_to_response, redirect, get_object_or_404
from subscription.models import Subscription
from subscription.forms import SubscriptionForm

def success(request, id):
    inscricao = True
    subscriber = get_object_or_404(Subscription, pk=id)
    return render_to_response("subscription/success.html", {"subs":subscriber, "inscricao":inscricao}, context_instance=RequestContext(request))
	
def subscription(request):
    inscricao = True    
    form = SubscriptionForm()
    
    if request.method == "POST":
	form = SubscriptionForm(request.POST)
    
	if not form.is_valid():
	    return render_to_response("subscription/form.html", {"form":form, "inscricao":inscricao}, context_instance=RequestContext(request))
	    
	get_form = form.save()
	return redirect("subscription:subs_success", id=get_form.pk)
    else:
	return render_to_response("subscription/form.html", {"form":form, "inscricao":inscricao}, context_instance=RequestContext(request))

testes/views.py
# Create your views here.

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>EventEX {% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}ui/css/estilos.css" />
	<link href='http://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
	{% block js %}{% endblock %}

</head>

<body>
	<div id="header">
		<h1 class="azul">EventEX</h1>
		<div class="nav">
			<ul>
				<li style="padding-right: 10px; border-right: 1px solid #03bcfd"><a href="{% url home %}" title="Hot Site"{% if home %}class="active"{% endif %}>Home</a></li>
				<li><a href="{% url subscription:subs_new %}" title="Inscrição"{% if inscricao %}class="active"{% endif %}>Inscrição</a></li>
			</ul>
		</div>
		<br class="clear" />
	</div>
	<div id="content">
		{% block content %} {% endblock %}
	</div>
	<div id="footer">
		<p></p>
	</div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %} Hot Site {% endblock %}

{% block content %}
<p>O evento mais sensacional depois do Dev in Rio</p>
<p>Você não pode perder esta oportunidade!</p>
<p><a href="{% url subscription:subs_new %}">Inscriões abertas CLIQUE AQUI.</a></p>
<p>Para dúvidas e mais informações entre em contato com <a href="mailto:eventex@eventex.com.br">eventex@eventex.com.br</a></p>
{% endblock %}

templates/subscription/form.html
{% extends "base.html" %}

{% block title %} Inscrição! {% endblock %}

{% block js %}
<script type="text/javascript" src="{{ STATIC_URL }}ui/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}ui/js/mask.js"></script>	
<script type="text/javascript">
	jQuery(function($) {
		$("#id_phone").mask("(99) 9999-9999");
		$("#id_cpf").mask("999.999.999-99");		
	});
</script>
{% endblock %}

{% block content %}
<p>Inscreva-se agora mesmo no evento mais sensacional do momento!</p>
<form action="{% url subscription:subs_new %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" name="submit" value="Inscrever" />
</form>
{% endblock %}

templates/subscription/success.html
{% extends "base.html" %}

{% block title %} Sucesso! {% endblock %}

{% block content %}
<p><span class="azul">{{ subs.name }}</span>, seu cadastro foi realizado com sucesso!</p>
<p>
	Aguarde... logo logo entraremos em contato pelo 
	{% if subs.phone %}
	telefone: <span class="azul">{{ subs.phone }}</span>
	{% else %}
	e-mail: <span class="azul">{{ subs.email }}</span>
	{% endif %}
</p>
{% endblock %}